repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.3.0
    hooks:
    - id: flakeheaven
